### ISSUE TITLE
Fixed-elements / Capturing Screenshots

### ISSUE THREAD

**Issue by ffalkner** [kdzwinel/Look-alike#1]
Hi. 
Fantastic Quick-test tool :-)
A Fixed Topmenubar makes Screenshots look "funny" when scrolled down and captured. Is it possible to ignore Fixed-element when scrolled?

Try it yourself on: www.citypack.dk

**Comment by rrfaria** [comment]
My suggestion to solve this issue to dev.

Analysis where is the fixed element bar if is on top or botton and take screenshot the other side:
for instance if element in top you start to the bottom leaving a margin size the same height of element and when you are on top you take a complete screenshot


make sense?

**Comment by oleggromov** [comment]
I don't know about how this particular extension is made but `puppeeter` has an option to take a full page screenshot. Then there will be no scrolling.

**Comment by kdzwinel** [comment]
Just released version [2.0.0](https://github.com/kdzwinel/Look-alike/releases/tag/v2.0.0) of the extension and it uses same technique of capturing screenshots as Chrome DevTools. Fixed elements will show up only once on screenshots now 🎉
